### PR TITLE
Basic Documentation

### PR DESCRIPTION
**Pull request by thazhemadam**
Set up basic documentation, and CI for hosting documentation.
The documentation largely contains existing documentation present in the wiki reworded and moved around a little.

[edit by Rachel to add Anant's nice summary from his email to me for the record]
I've included almost everything you've put in the wiki, and reworded
things a little in a few places, and moved some things around. I
decided to drop the "Basic Architecture" subsection seeing as it was
only explaining the basic architecture of any CNN (convolutional
layers, pooling layers, and fully connected layers).
I've also taken the liberty of including an additional section
explaining how and why GCNNs are a good idea for tasks like this.
The only things "pending" are documentation of the examples (for
AtomicGraphNets) and documentation pertaining to the interfaces and
functions the package provides (for both AtomicGraphNets and
ChemistryFeaturization), but I don't feel that is as important for
AtomicGraphNets as it is for ChemistryFeaturization.

For most of the equations, and matrices, I used LaTex instead, and
imported whatever images I needed into a separate directory. I assume
that would mean that we could delete the "img" folder entirely, unless
you have something else in mind for those assets.

### CODE REVIEW

**Comment by thazhemadam** [comment]
The entire `img` directory can now be removed (if you decide to edit the existing wiki accordingly), as the documentation doesn't depend on those assets.

**Comment by SinaMostafanejad** [comment]
Thanks @thazhemadam for making this PR. I had made a fork and was about to propose similar changes for getting the Documenter.jl up and running.

In your documentation workflow:

- Line 12: While the CI workflow tests the package for other OSs and architectures such as Windows and MAC-OS as well, you are not considering any of those cases here. Is there any specific reason to narrow this choice down to Linux Ubuntu here?

https://github.com/aced-differentiate/AtomicGraphNets.jl/pull/53/commits/51ba5aad3257ebd6e673c16ac6ebd8ba691e9314#diff-41e0ea85f266acbb46726d770d4324c0559e854f260066d459ff0a42c6947c67R12

- Line 17, you've chosen Julia v1.4 while in CI.yml, the Julia version variable has been set to a range for all v1.x versions. Why not expanding the build to other Julia versions here as well?

https://github.com/aced-differentiate/AtomicGraphNets.jl/pull/53/commits/51ba5aad3257ebd6e673c16ac6ebd8ba691e9314#diff-41e0ea85f266acbb46726d770d4324c0559e854f260066d459ff0a42c6947c67R17

- Do you need lines 19-20 (same goes for CI.yml file in lines 11-12 https://github.com/aced-differentiate/AtomicGraphNets.jl/blob/master/.github/workflows/CI.yml#L11-L12)?

https://github.com/aced-differentiate/AtomicGraphNets.jl/pull/53/commits/51ba5aad3257ebd6e673c16ac6ebd8ba691e9314#diff-41e0ea85f266acbb46726d770d4324c0559e854f260066d459ff0a42c6947c67R19-R20

**Comment by SinaMostafanejad** [comment]
In another comment regarding issue #14 and PR #53:
Pull Requests and issues can be linked together (see the last tab on the right-hand side menu of this page) so that when you merge a PR, the pertinent linked issue will be automatically closed as well. 
You can also use keywords such as "resolves #14" or similar words in your PR description or commit messages to link the issue to your PR for automatic closure with PR merge.

See: https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue

**Comment by thazhemadam** [comment]
> In another comment regarding issue #14 and PR #53:
> 
> Pull Requests and issues can be linked together (see the last tab on the right-hand side menu of this page) so that when you merge a PR, the pertinent linked issue will be automatically closed as well.
> You can also use keywords such as "resolves #14" or similar words in your PR description or commit messages to link the issue to your PR for automatic closure with PR merge.
> 
> See: https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue

The documentation is yet to better cover the details regarding functions and interfaces provided. Since there's still work left to be done, I didn't request for closure of the issue just yet.

**Comment by rkurchin** [comment]
Merging this into my new `add_docs` branch so I can make a few tweaks before deploying. Thanks again @thazhemadam for the awesome work setting this up! 😁

**Pull request merged**
